name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy-robokinesis:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        shell: bash
        working-directory: projects/robokinesis
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - run: |
          npm install
          npm run ghactionsbootstrap --force
          npm run build
      
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          USER: root
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}

  deploy-modularbots:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        shell: bash
        working-directory: projects/modularbots
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - run: |
          npm install
          npm run ghactionsbootstrap --force
          npm run build
      
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          USER: root
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}

  deploy-netbots:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        shell: bash
        working-directory: projects/netbots
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.2.0
      - run: |
          npm install
          npm run ghactionsbootstrap --force
          npm run build
      
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          USER: root
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}